import Footer from "@/components/layout/footer";
import Menu from "@/components/layout/menu";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Bitter } from "next/font/google";

const bitter = Bitter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Split App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html>
      <body className={`${bitter.className} m-4`}>
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
