import Footer from "@/components/footer/footer";
import Menu from "@/components/menu/menu";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Bitter } from "next/font/google";

const bitter = Bitter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bitter.className} m-4`}>
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
